name: Create Release ZIP

on:
  release:
    types:
      - created

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: zip -r release.zip . -x '*.git*' '*.github*'

      - name: Upload ZIP file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release.zip
          asset_name: release.zip
          asset_content_type: application/zip
